version: '3.8'

services:
  category-management:
    image: category-management:latest
    container_name: category-management
    build:
      context: ./category-management
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:h2:mem:categorydb
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: password
    ports:
      - "8081:8081"
    networks:
      - library-network

  elements-management:
    image: elements-management:latest
    container_name: elements-management
    build:
      context: ./elements-management
    environment:
      SPRING_PROFILES_ACTIVE: docker
      DATABASE_URL: jdbc:h2:mem:elementdb
      DATABASE_USERNAME: sa
      DATABASE_PASSWORD: password
    ports:
      - "8082:8082"
    networks:
      - library-network

  gateway:
    image: gateway:latest
    container_name: gateway
    build:
      context: ./gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    networks:
      - library-network

  angular-app:
    image: angular-app:latest
    container_name: angular-app
    build:
      context: ./library-frontend
    environment:
      API_GATEWAY: "http://gateway:8080"
    ports:
      - "4200:80"
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
